# List of item display names that should not be dropped on player death
whitelist-item-names:
  - "Diamond Sword"
  - "Special Axe"

# List of item IDs (Materials) that should not be dropped on player death
whitelist-item-ids: []

# Option to allow players to keep whitelisted items on respawn
keep-whitelisted-items: true
